#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -eq 0 ]; then
  echo "Usage : "
  echo "  -  $0 14242 CORE org.apache.spark.deploy.SparkSubmitSuite"
  echo "  -  $0 15253 SparkR"
  exit 1
fi

PR_NUM=$1
COMPONENT=$2
SUITE=$3
BRANCH=`uuidgen`

# Fetch the pull request.
cd "$(cd "`dirname $0`"/spark; pwd)"
git fetch upstream refs/pull/$PR_NUM/head:$BRANCH

# Generate appveyor.yml
../gen-appveyor-yml $COMPONENT $SUITE

# Push the updated appveyor.yml.
git checkout $BRANCH
git add appveyor.yml
git commit -m "Pull Reqeust: $1"
git push origin $BRANCH

# Checkout back to the master
git checkout master

cd "$SPDIR"
url=`git remote -v | grep origin | grep push`
replaced=$(echo $url | sed -e "s/.*github\.com\///g")
org=$(echo $replaced | sed -e "s/\/spark\.git.*//g")

if [ -z "$SUITE" ]; then
  SUITE="ALL"
fi

echo "Build started: [$COMPONENT] \`$SUITE\` [![PR-$PR_NUM](https://ci.appveyor.com/api/projects/status/github/$org/spark?branch=$BRANCH&svg=true)](https://ci.appveyor.com/project/$org/spark/branch/$BRANCH)"
