#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -eq 0 ]; then
    echo "Usage : init https://github.com/spark-test/spark.git"
  exit 1
fi

FWDIR="$(cd "`dirname $0`"/..; pwd)"
cd "$FWDIR"
SPARK_URL=$1

git clone $SPARK_URL
cd spark
git remote add upstream https://github.com/apache/spark.git

echo '[remote "upstream"]' >> .git/config
echo '        url = https://github.com/apache/spark.git' >> .git/config
echo '        fetch = +refs/heads/*:refs/remotes/upstream/*' >> .git/config
echo '        fetch = +refs/pull/*/head:refs/remotes/origin/pr/*' >> .git/config

git fetch upstream
