#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -eq 0 ]
  then
    echo "Usage : gen-appveyor CORE org.apache.spark.deploy.SparkSubmitSuite"
    echo "Usage : gen-appveyor SparkR"
fi

COMPONENT=$1
SUITE=$2
SPDIR="$(cd "`dirname $0`"/../spark; pwd)"
cd "$SPDIR"
ETCDIR="$(cd "`dirname $0`"/../etc; pwd)"

if [ "$COMPONENT" == "SparkR" ]; then
   # R
   cp -f $ETCDIR/appveyor-r.yml.template $SPDIR/appveyor.yml
else
   # Scala
   cp -f $ETCDIR/appveyor-scala.yml.template $SPDIR/appveyor.yml
   echo "test_script:" >> appveyor.yml
   echo "  - cmd: sbt 'test-only $SUITE'" >> appveyor.yml
   echo  >> appveyor.yml
fi

